### ISSUE TITLE
Countdown animation

### ISSUE THREAD

**Issue by Ornolfr** [vorlovsky/flipper-android#1]
Hello.
It's nice that countdown is working in this library but the animation remains old and designed for counting up. Could you improve it to work both for counting down and up?

**Comment by vorlovsky** [comment]
Hi!
What improvement do you mean?
The animation is designed to simulate flipping "leafs" while one character is changing to another one.
Do you want a leaf to go upwards in the case of countdown?

**Comment by Ornolfr** [comment]
@vorlovsky Yeah, I would like that.

**Comment by vorlovsky** [comment]
It sounds nonsense, nevertheless it's done.)
